### ISSUE TITLE
plot trends on a graph

### ISSUE THREAD

**Issue by cartoloupe** [cartoloupe/drift#25]
possible technologies:
- d3
- highcharts
- ruport

[maybe a line chart like this](https://bl.ocks.org/mbostock/3883245):
<img width="737" alt="screen shot 2016-03-25 at 10 47 39 pm" src="https://cloud.githubusercontent.com/assets/4593934/14057613/9be8f80e-f2db-11e5-84c6-53c1bc0dd16e.png">

**Comment by degoeym** [comment]
If we plan to put this out in some sort of commercial aspect, I wouldn't vote for highcharts as they have licensing.

I also found this:

http://chartkick.com/

**Comment by cartoloupe** [comment]
chartkick ++
